services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - '6379:6379' # for redis
      - '8001:8001' # for redis stack
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
